name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. دریافت پروژه
      - name: Checkout
        uses: actions/checkout@v5

      # 2. نصب Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      # 3. نصب Java 21
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      # 4. نصب وابستگی‌های اصلی پروژه
      - name: Install project dependencies
        run: npm install

      # 5. نصب Capacitor
      - name: Install Capacitor
        run: npm install --no-save @capacitor/core@7 @capacitor/cli@7 @capacitor/android@7

      # 6. ساخت نسخه وب پروژه
      - name: Build web app
        run: npm run build

      # 7. همگام‌سازی Capacitor با Android
      - name: Sync Capacitor Android
        run: npx cap sync android

      # 8. دادن دسترسی اجرا به Gradle
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        working-directory: android

      # 9. ساخت APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: android

      # 10. آپلود APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Planer1-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
